# Generated by Django 5.2.17 on 2026-08-31 03:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("runtime_resources", models.JSONField(default=dict)),
                (
                    "observed_readiness",
                    models.CharField(default="unknown", max_length=24),
                ),
                ("worker_placement", models.CharField(blank=True, max_length=253)),
                ("console_endpoints", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("privileged", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="LabDeployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_desired_state",
                    models.CharField(default="running", max_length=20),
                ),
                (
                    "observed_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("deploying", "Deploying"),
                            ("running", "Running"),
                            ("degraded", "Degraded"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                            ("deleting", "Deleting"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("cluster_identity", models.CharField(max_length=255)),
                ("namespace", models.CharField(max_length=253, unique=True)),
                ("resource_identities", models.JSONField(default=dict)),
                ("runtime_version", models.CharField(max_length=40)),
                ("last_reconciliation", models.DateTimeField(blank=True, null=True)),
                ("error_details", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LabInterface",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("shared_medium", models.BooleanField(default=False)),
                ("reserved_management", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ConfigurationVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("version", models.PositiveIntegerField()),
                ("encrypted_content", models.BinaryField()),
                ("checksum", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsoleSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("read_only", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.deviceinstance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("containerlab_kind", models.CharField(max_length=80)),
                ("launch_profile", models.JSONField(default=dict)),
                ("interface_rules", models.JSONField(default=dict)),
                ("image_requirements", models.JSONField(default=dict)),
                ("resource_requirements", models.JSONField(default=dict)),
                ("console_method", models.CharField(default="ssh", max_length=20)),
                ("readiness_checks", models.JSONField(default=list)),
                ("configuration_operations", models.JSONField(default=list)),
                ("capabilities", models.JSONField(default=dict)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="studio.devicetemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="devicetemplate",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="studio.devicetemplateversion",
            ),
        ),
        migrations.CreateModel(
            name="ImageArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("detected_format", models.CharField(max_length=40)),
                ("byte_size", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=64, unique=True)),
                ("vendor", models.CharField(blank=True, max_length=80)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("version", models.CharField(blank=True, max_length=80)),
                ("architecture", models.CharField(blank=True, max_length=20)),
                ("storage_reference", models.CharField(max_length=512)),
                ("license_acknowledged", models.BooleanField(default=False)),
                ("inspection_result", models.JSONField(default=dict)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("quarantined", "Quarantined"),
                            ("inspecting", "Inspecting"),
                            ("validated", "Validated"),
                            ("unsupported", "Unsupported"),
                            ("failed", "Failed"),
                        ],
                        default="quarantined",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImageBuild",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipe_version", models.CharField(max_length=80)),
                ("job_identity", models.CharField(max_length=253, unique=True)),
                ("status", models.CharField(default="pending", max_length=24)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("log_reference", models.CharField(blank=True, max_length=512)),
                ("failure_details", models.JSONField(default=dict)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="builds",
                        to="studio.imageartifact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LabArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artifact_type", models.CharField(max_length=32)),
                ("storage_reference", models.CharField(max_length=512)),
                ("checksum", models.CharField(max_length=64)),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="studio.labdeployment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="deviceinstance",
            name="deployment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="studio.labdeployment",
            ),
        ),
        migrations.CreateModel(
            name="CaptureSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="pending", max_length=24)),
                ("expires_at", models.DateTimeField()),
                ("artifact_reference", models.CharField(blank=True, max_length=512)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.labdeployment",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studio.labinterface",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LabNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=63)),
                ("position", models.JSONField(default=dict)),
                ("properties", models.JSONField(default=dict)),
                (
                    "startup_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studio.configurationversion",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studio.devicetemplateversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="labinterface",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interfaces",
                to="studio.labnode",
            ),
        ),
        migrations.AddField(
            model_name="deviceinstance",
            name="lab_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="studio.labnode"
            ),
        ),
        migrations.CreateModel(
            name="LabRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_number", models.PositiveIntegerField()),
                ("topology_checksum", models.CharField(max_length=64)),
                ("immutable", models.BooleanField(default=False)),
                ("canvas_layout", models.JSONField(default=dict)),
                ("annotations", models.JSONField(default=list)),
                ("edit_version", models.PositiveIntegerField(default=1)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="studio.lab",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="labnode",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="studio.labrevision",
            ),
        ),
        migrations.CreateModel(
            name="LabLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("properties", models.JSONField(default=dict)),
                (
                    "endpoint_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_as_a",
                        to="studio.labinterface",
                    ),
                ),
                (
                    "endpoint_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_as_b",
                        to="studio.labinterface",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="studio.labrevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="labdeployment",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployments",
                to="studio.labrevision",
            ),
        ),
        migrations.AddField(
            model_name="lab",
            name="current_draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="draft_for_labs",
                to="studio.labrevision",
            ),
        ),
        migrations.CreateModel(
            name="OperationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_type", models.CharField(max_length=40)),
                ("target_id", models.UUIDField()),
                ("idempotency_key", models.CharField(max_length=128)),
                ("state", models.CharField(default="accepted", max_length=24)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("heartbeat", models.DateTimeField(blank=True, null=True)),
                ("error_details", models.JSONField(default=dict)),
                (
                    "deployment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="studio.labdeployment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("quotas", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lab",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="labs",
                to="studio.project",
            ),
        ),
        migrations.CreateModel(
            name="ImageCredentialReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("secret_name", models.CharField(max_length=253)),
                ("registry_host", models.CharField(max_length=253)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="studio.project"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="imageartifact",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_artifacts",
                to="studio.project",
            ),
        ),
        migrations.AddField(
            model_name="configurationversion",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="studio.project"
            ),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("target_type", models.CharField(max_length=80)),
                ("target_id", models.UUIDField(null=True)),
                ("correlation_id", models.CharField(max_length=128)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("administrator", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="studio.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registry_digest", models.CharField(max_length=255, unique=True)),
                ("repository", models.CharField(max_length=255)),
                ("architecture", models.CharField(max_length=20)),
                ("compatibility_result", models.JSONField(default=dict)),
                (
                    "lifecycle_status",
                    models.CharField(default="unverified", max_length=24),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_images",
                        to="studio.imageartifact",
                    ),
                ),
                (
                    "build",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studio.imagebuild",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="labnode",
            name="published_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="studio.publishedimage",
            ),
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "expected_size",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("received_bytes", models.BigIntegerField(default=0)),
                ("received_parts", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("expected_checksum", models.CharField(max_length=64)),
                ("computed_checksum", models.CharField(blank=True, max_length=64)),
                ("artifact_destination", models.CharField(max_length=512)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_sessions",
                        to="studio.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="imageartifact",
            name="upload_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifact",
                to="studio.uploadsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="devicetemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="unique_template_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="labinterface",
            constraint=models.UniqueConstraint(
                fields=("node", "name"), name="unique_interface_per_node"
            ),
        ),
        migrations.AddConstraint(
            model_name="deviceinstance",
            constraint=models.UniqueConstraint(
                fields=("deployment", "lab_node"), name="unique_deployment_node"
            ),
        ),
        migrations.AddConstraint(
            model_name="labrevision",
            constraint=models.UniqueConstraint(
                fields=("lab", "revision_number"), name="unique_lab_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="lablink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("endpoint_a", models.F("endpoint_b")), _negated=True
                ),
                name="link_distinct_endpoints",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationjob",
            constraint=models.UniqueConstraint(
                fields=("owner", "idempotency_key"), name="unique_owner_idempotency"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["accepted", "scheduled", "started"])),
                fields=("target_id", "operation_type"),
                name="one_active_target_operation",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_project_name_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="lab",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_lab_name_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="imagecredentialreference",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_credential_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationversion",
            constraint=models.UniqueConstraint(
                fields=("project", "name", "version"), name="unique_config_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_project_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="labnode",
            constraint=models.UniqueConstraint(
                fields=("revision", "name"), name="unique_node_name_per_revision"
            ),
        ),
    ]
