# Generated by Django 5.2.17 on 2026-08-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0005_capture_session_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageartifact",
            name="checksum",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="uploadsession",
            name="expected_checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="imageartifact",
            constraint=models.UniqueConstraint(
                fields=("project", "checksum"), name="unique_image_checksum_per_project"
            ),
        ),
    ]
