# Generated by Django 5.2.17 on 2026-08-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0006_alter_imageartifact_checksum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="license_acknowledged",
            field=models.BooleanField(default=False),
        ),
    ]
