# Generated by Django 5.2.17 on 2026-09-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0010_configure_runtime_collectors"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="imageartifact",
            name="unique_image_checksum_per_project",
        ),
        migrations.AddField(
            model_name="imageartifact",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="imageartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "checksum"),
                name="unique_active_image_checksum_per_project",
            ),
        ),
    ]
