# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("studio", "0011_soft_delete_image_artifacts")]
    operations = [
        migrations.RemoveConstraint(model_name="lab", name="unique_lab_name_per_project"),
        migrations.AddField(model_name="lab", name="deleted_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddConstraint(model_name="lab", constraint=models.UniqueConstraint(
            condition=models.Q(("deleted_at__isnull", True)), fields=("project", "name"), name="unique_active_lab_name_per_project")),
    ]
