# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("studio", "0012_soft_delete_labs")]
    operations = [
        migrations.RemoveConstraint(model_name="project", name="unique_project_name_per_owner"),
        migrations.AddField(model_name="project", name="deleted_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddConstraint(model_name="project", constraint=models.UniqueConstraint(
            condition=models.Q(("deleted_at__isnull", True)), fields=("owner", "name"), name="unique_active_project_name_per_owner")),
    ]
