# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("studio", "0013_soft_delete_projects")]
    operations = [
        migrations.AddField(model_name="labdeployment", name="removed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AlterField(model_name="labdeployment", name="observed_state", field=models.CharField(
            choices=[("pending", "Pending"), ("deploying", "Deploying"), ("running", "Running"), ("degraded", "Degraded"),
                ("failed", "Failed"), ("stopped", "Stopped"), ("deleting", "Deleting"), ("removed", "Removed")],
            default="pending", max_length=20)),
    ]
