# Generated by Django 5.2.17 on 2026-09-01 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0016_user_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="studio.labfolder",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_folders",
                        to="studio.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lab",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="labs",
                to="studio.labfolder",
            ),
        ),
        migrations.AddConstraint(
            model_name="labfolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("parent__isnull", True)
                ),
                fields=("project", "name"),
                name="unique_active_root_lab_folder",
            ),
        ),
        migrations.AddConstraint(
            model_name="labfolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("parent__isnull", False)
                ),
                fields=("project", "parent", "name"),
                name="unique_active_nested_lab_folder",
            ),
        ),
    ]
