# Generated by Django 5.2.17 on 2026-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0018_deploymentschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagebuild",
            name="log_excerpt",
            field=models.TextField(blank=True),
        ),
    ]
