# Generated by Django 5.2.17 on 2026-09-01 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0019_imagebuild_log_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageartifact",
            name="credential_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_artifacts",
                to="studio.imagecredentialreference",
            ),
        ),
        migrations.AddField(
            model_name="imagecredentialreference",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_image_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imagecredentialreference",
            name="credential_type",
            field=models.CharField(
                choices=[("basic", "Basic"), ("token", "Token")],
                default="basic",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="imagecredentialreference",
            name="encrypted_secret",
            field=models.BinaryField(blank=True, default=bytes),
        ),
        migrations.AddField(
            model_name="imagecredentialreference",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="imagecredentialreference",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagecredentialreference",
            name="secret_fingerprint",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="imagecredentialreference",
            name="username",
            field=models.CharField(blank=True, max_length=253),
        ),
        migrations.AlterField(
            model_name="imagecredentialreference",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="image_credentials",
                to="studio.project",
            ),
        ),
        migrations.AlterField(
            model_name="imagecredentialreference",
            name="secret_name",
            field=models.CharField(
                blank=True,
                help_text="Optional externally managed Kubernetes Secret name",
                max_length=253,
            ),
        ),
    ]
