import { Terminal } from '@xterm/xterm';
import '@xterm/xterm/css/xterm.css';
import './console.css';
import { requestedConsoleDevice } from './console-utils';

type Device={id:string;node_id:string;name:string;kind:string;observed_readiness:string};
const deployment=new URLSearchParams(location.search).get('deployment')||'';
let requestedDevice=new URLSearchParams(location.search).get('device')||'';
const root=document.getElementById('console-app')!;
const csrf=()=>document.cookie.split('; ').find(x=>x.startsWith('csrftoken='))?.split('=')[1]||'';
root.innerHTML='<header><div><strong>Device consoles</strong><small>Authenticated sessions expire after 15 minutes</small></div><span id="connection-state">Select a device</span></header><nav id="device-tabs"></nav><main id="terminal-host"><div class="console-empty">Choose a ready device to open its console.</div></main>';
let socket:WebSocket|null=null,terminal:Terminal|null=null;
async function load(){const response=await fetch(`/api/v1/deployments/${deployment}/runtime/`);if(!response.ok)throw new Error('Unable to load runtime devices');const data=await response.json();const devices:Device[]=data.devices;document.getElementById('device-tabs')!.innerHTML=devices.map(device=>`<button data-device="${device.id}" ${device.observed_readiness!=='ready'?'disabled':''}><i></i>${device.name}<small>${device.observed_readiness}</small></button>`).join('')||'<span>No runtime devices discovered</span>';document.querySelectorAll<HTMLButtonElement>('[data-device]').forEach(button=>button.onclick=()=>openConsole(button.dataset.device!,button.textContent||'device'));const requested=devices.find(device=>device.id===requestedDevice&&device.observed_readiness==='ready');if(requested){requestedDevice='';await openConsole(requested.id,requested.name)}}
async function openConsole(deviceId:string,name:string){socket?.close();terminal?.dispose();document.querySelectorAll('[data-device]').forEach(x=>x.classList.toggle('active',(x as HTMLElement).dataset.device===deviceId));const host=document.getElementById('terminal-host')!;host.innerHTML='';terminal=new Terminal({cursorBlink:true,fontFamily:'JetBrains Mono, monospace',fontSize:13,theme:{background:'#050c14',foreground:'#d7e7ef',cursor:'#26c6da',selectionBackground:'#244863'},scrollback:5000});terminal.open(host);terminal.writeln(`\x1b[36mConnecting to ${name.trim()}…\x1b[0m`);const response=await fetch(`/api/v1/deployments/${deployment}/consoles/`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRFToken':csrf()},body:JSON.stringify({device_id:deviceId})});const session=await response.json();if(!response.ok){terminal.writeln(`\x1b[31m${session.error?.details||session.error?.code||'Console authorization failed'}\x1b[0m`);return}const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}${session.websocket}`);socket.onopen=()=>{document.getElementById('connection-state')!.textContent='Connecting…'};socket.onmessage=event=>{const message=JSON.parse(event.data);if(message.type==='output')terminal?.write(message.data);if(message.type==='status'){document.getElementById('connection-state')!.textContent=message.state;terminal?.writeln(`\r\n\x1b[90m[${message.state}]\x1b[0m`)}if(message.type==='error')terminal?.writeln(`\r\n\x1b[31m${message.message}\x1b[0m`)};socket.onclose=()=>{document.getElementById('connection-state')!.textContent='Disconnected'};terminal.onData(data=>{if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'input',data}))});setTimeout(()=>{if(terminal&&socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'resize',columns:terminal.cols,rows:terminal.rows}))},500);}
window.addEventListener('message',event=>{const deviceId=requestedConsoleDevice(event.origin,location.origin,event.data);if(!deviceId)return;requestedDevice=deviceId;const button=document.querySelector<HTMLButtonElement>(`[data-device="${CSS.escape(requestedDevice)}"]`);if(button&&!button.disabled){requestedDevice='';openConsole(button.dataset.device!,event.data.name||button.textContent||'device')}});
load().catch(error=>root.innerHTML=`<div class="console-error">${error.message}</div>`);
